### PR TITLE
Alter _getLoadSelect method when store_id exists

### PR DESCRIPTION
**Pull request by bertterheide**
This issue occurred when this code was executed through a command line tool.

### CODE REVIEW

**Comment by bertterheide** [comment]
@clockworkgeek, will this issue be merged?

**Comment by clockworkgeek** [comment]
@bertterheide Thank you for your submission.

How can I recreate the issue?  Does it also occur with [this branch](https://github.com/Knectar/Magento-Store-Codes/tree/unique-domain)?

**Comment by bertterheide** [comment]
@clockworkgeek,

in file ```app/code/community/Knectar/Storecodes/Model/Resource/Cms/Page.php``` on line 46 you expect store_id to exist in the created ```$select``` query, while the extended class ```Mage_Cms_Model_Resource_Page``` only adds this join when store_id exists on ```$object```. 

Can you look into this?

Thanks.

**Comment by clockworkgeek** [comment]
I still cannot recreate this but it's defensive programming and I approve of that in general.

**Pull request merged**
